Fix ``AttributeError: 'module' object has no attribute 'client'``.
Began showing up when a site that was using the Ezi switched off a component that was importing ``suds.client``, causing these ``AttributeError`` messages to begin showing up. I wasn't aware that a ``suds.client`` import in a separate file would change the contents of ``suds`` when used in unrelated modules, ie. ``dir(suds)`` no longer showed ``client`` after the unrelated module was switched off.